server:
  port: 8410
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_management
    password: Jesus1234
    username: muzuri

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true

  resources:

  web:
    resources:
      add-mappings: false